### ISSUE TITLE
Editor Prints extra whitespace on exiting

### ISSUE THREAD

**Issue by ghost** [Eyesonjune18/rut#1]
![image](https://user-images.githubusercontent.com/96284645/216217572-1808968d-2576-4270-8955-399f241013ec.png)

**Comment by ghost** [comment]
Might be an issue with the clear screen function

**Comment by ghost** [comment]
seems to only be doing this on linux
(Im on arch right now)
You should test it on some other peoples systems on linux to check if this is only a linux issue or just a issue with crossterm

**Comment by lthoerner** [comment]
This was an issue related to crossterm's default behavior to not clear the terminal scrollback buffer, aka "history" (see https://github.com/crossterm-rs/crossterm/pull/591). Because I am using the tui crate now, I am going to mark this as closed. If the issue is still present when using tui, I will reopen it.
